ALTER TABLE public."Profile" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."Client" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."Proposal" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."ConnectsLog" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."Template" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."ActivityLog" DISABLE ROW LEVEL SECURITY;
